import type { SupportedLocale } from '@/domain/catalogue';

export const catalogueCopy = {
  en: {
    title: 'Explore running shoes',
    intro:
      'Search and compare the complete catalogue by purpose, surface, guidance, and construction.',
    searchLabel: 'Search products',
    searchPlaceholder: 'Search by brand, model or technology',
    suggestions: 'Search suggestions',
    searchDecathlon: (query: string) => `Search Decathlon for “${query}”`,
    consultationTitle: 'Help a customer choose the right shoe',
    consultationDescription:
      'Answer a short questionnaire with the customer to find explainable matches.',
    consultationAction: 'Start customer consultation',
    allCategories: 'All categories',
    purposeCategories: 'Purpose',
    surfaceAndTerrain: 'Surface & terrain',
    results: (shown: number, total: number) => `${shown} of ${total} shoes`,
    noResults: 'No shoes match these filters.',
    clearFilters: 'Clear filters',
    details: 'Details',
    compare: 'Compare',
    remove: 'Remove',
    selected: 'Selected',
    comparisonSelection: 'Shoe comparison selection',
    deselectProduct: (model: string) => `Deselect ${model}`,
    compareSelected: (count: number) => `Compare selected (${count}/2)`,
    previous: 'Previous',
    next: 'Next',
    page: (current: number, total: number) => `Page ${current} of ${total}`,
    bestFor: 'Best for',
    distance: 'Distance',
    distanceUnavailable: 'Not published',
    surface: 'Surface',
    terrain: 'Terrain',
    stability: 'Stability',
    drop: 'Drop',
    pending: 'Pending',
    notApplicable: 'Not applicable',
    technologies: 'Construction & technologies',
    ride: 'Ride & intended use',
    sources: 'Sources',
    weight: 'Weight reference',
    weightValue: 'Weight',
    sourcePending: 'Source verification pending',
    productOverview: 'Product overview',
    constructionAndRide: 'Construction & ride',
    rideCharacter: 'Ride character',
    support: 'Stability & guidance',
    upper: 'Upper',
    midsole: 'Midsole',
    outsole: 'Outsole / grip',
    fit: 'Fit',
    stackHeight: 'Stack height',
    plateSystem: 'Plate / system',
    strengthsAndLimitations: 'Strengths & limitations',
    strengthsLead:
      'A concise view migrated from the original RunDecoded prototype.',
    bestAt: 'Best at',
    lessSuitableFor: 'Less suitable for',
    sourceProduct: 'View on Decathlon',
    prototypeEvidence: 'Prototype evidence',
    verifiedEvidence: 'Verified product source',
    detailsPending:
      'The original prototype did not contain a full detail profile for this exact model. Verification is pending.',
    comparableProducts: 'Comparable products',
    compareWith: (model: string) => `Compare with ${model}`,
    openDetails: (model: string) => `Open details for ${model}`,
    productImage: (model: string) => `Product image for ${model}`,
    imagePending: 'Official product image pending',
    comparisonTitle: 'Shoe comparison',
    comparisonDescription:
      'Compare purpose and technical facts. Differences are guidance, not a personal fit recommendation.',
    differenceSummary: 'Key differences',
    characteristic: 'Characteristic',
    category: 'Category',
    different: 'Different',
    same: 'Same',
    notCompared: 'Not compared',
    weightReferenceMismatch:
      'Reference sizes differ, so weight is not highlighted.',
    selectionLimit:
      'Two shoes are already selected. Remove one before adding another.',
  },
  de: {
    title: 'Laufschuhe entdecken',
    intro:
      'Durchsuche und vergleiche den vollständigen Katalog nach Einsatzzweck, Untergrund, Führung und Konstruktion.',
    searchLabel: 'Produkte suchen',
    searchPlaceholder: 'Nach Marke, Modell oder Technologie suchen',
    suggestions: 'Suchvorschläge',
    searchDecathlon: (query: string) => `Bei Decathlon nach „${query}“ suchen`,
    consultationTitle: 'Den passenden Schuh für einen Kunden finden',
    consultationDescription:
      'Beantworte gemeinsam mit dem Kunden einige Fragen und erhalte nachvollziehbare Empfehlungen.',
    consultationAction: 'Kundenberatung starten',
    allCategories: 'Alle Kategorien',
    purposeCategories: 'Einsatzzweck',
    surfaceAndTerrain: 'Untergrund & Gelände',
    results: (shown: number, total: number) => `${shown} von ${total} Schuhen`,
    noResults: 'Keine Schuhe passen zu diesen Filtern.',
    clearFilters: 'Filter löschen',
    details: 'Details',
    compare: 'Vergleichen',
    remove: 'Entfernen',
    selected: 'Ausgewählt',
    comparisonSelection: 'Schuhauswahl für den Vergleich',
    deselectProduct: (model: string) => `${model} abwählen`,
    compareSelected: (count: number) => `Auswahl vergleichen (${count}/2)`,
    previous: 'Zurück',
    next: 'Weiter',
    page: (current: number, total: number) => `Seite ${current} von ${total}`,
    bestFor: 'Geeignet für',
    distance: 'Distanz',
    distanceUnavailable: 'Nicht veröffentlicht',
    surface: 'Untergrund',
    terrain: 'Gelände',
    stability: 'Stabilität',
    drop: 'Sprengung',
    pending: 'Ausstehend',
    notApplicable: 'Nicht zutreffend',
    technologies: 'Konstruktion & Technologien',
    ride: 'Laufgefühl & Einsatzzweck',
    sources: 'Quellen',
    weight: 'Gewichtsreferenz',
    weightValue: 'Gewicht',
    sourcePending: 'Quellenprüfung ausstehend',
    productOverview: 'Produktbeschreibung',
    constructionAndRide: 'Konstruktion & Laufgefühl',
    rideCharacter: 'Laufgefühl',
    support: 'Stabilität & Führung',
    upper: 'Upper / Schaft',
    midsole: 'Zwischensohle',
    outsole: 'Außensohle / Grip',
    fit: 'Passform',
    stackHeight: 'Stackhöhe',
    plateSystem: 'Platte / System',
    strengthsAndLimitations: 'Stärken & Grenzen',
    strengthsLead:
      'Kurze Einordnung, übernommen aus dem ursprünglichen RunDecoded-Prototyp.',
    bestAt: 'Besonders stark bei',
    lessSuitableFor: 'Weniger geeignet für',
    sourceProduct: 'Bei Decathlon ansehen',
    prototypeEvidence: 'Prototyp-Datengrundlage',
    verifiedEvidence: 'Geprüfte Produktquelle',
    detailsPending:
      'Der ursprüngliche Prototyp enthielt für dieses exakte Modell kein vollständiges Detailprofil. Die Prüfung steht noch aus.',
    comparableProducts: 'Vergleichbare Produkte',
    compareWith: (model: string) => `Mit ${model} vergleichen`,
    openDetails: (model: string) => `Details für ${model} öffnen`,
    productImage: (model: string) => `Produktbild für ${model}`,
    imagePending: 'Offizielles Produktbild ausstehend',
    comparisonTitle: 'Schuhvergleich',
    comparisonDescription:
      'Vergleiche Einsatzzweck und technische Fakten. Unterschiede ersetzen keine persönliche Passformberatung.',
    differenceSummary: 'Wichtigste Unterschiede',
    characteristic: 'Merkmal',
    category: 'Kategorie',
    different: 'Unterschiedlich',
    same: 'Gleich',
    notCompared: 'Nicht verglichen',
    weightReferenceMismatch:
      'Die Referenzgrößen unterscheiden sich; das Gewicht wird deshalb nicht hervorgehoben.',
    selectionLimit:
      'Zwei Schuhe sind bereits ausgewählt. Entferne einen, bevor du einen weiteren hinzufügst.',
  },
  fr: {
    title: 'Explorer les chaussures',
    intro:
      'Recherchez et comparez le catalogue complet selon l’usage, le terrain, le guidage et la construction.',
    searchLabel: 'Rechercher des produits',
    searchPlaceholder: 'Rechercher par marque, modèle ou technologie',
    suggestions: 'Suggestions de recherche',
    searchDecathlon: (query: string) => `Rechercher « ${query} » sur Decathlon`,
    consultationTitle: 'Aider un client à choisir la bonne chaussure',
    consultationDescription:
      'Répondez à quelques questions avec le client pour obtenir des recommandations explicables.',
    consultationAction: 'Démarrer le conseil client',
    allCategories: 'Toutes les catégories',
    purposeCategories: 'Usage',
    surfaceAndTerrain: 'Surface et terrain',
    results: (shown: number, total: number) =>
      `${shown} chaussures sur ${total}`,
    noResults: 'Aucune chaussure ne correspond à ces filtres.',
    clearFilters: 'Effacer les filtres',
    details: 'Détails',
    compare: 'Comparer',
    remove: 'Retirer',
    selected: 'Sélectionnée',
    comparisonSelection: 'Sélection de chaussures à comparer',
    deselectProduct: (model: string) => `Désélectionner ${model}`,
    compareSelected: (count: number) => `Comparer la sélection (${count}/2)`,
    previous: 'Précédent',
    next: 'Suivant',
    page: (current: number, total: number) => `Page ${current} sur ${total}`,
    bestFor: 'Idéale pour',
    distance: 'Distance',
    distanceUnavailable: 'Non publiée',
    surface: 'Terrain',
    terrain: 'Profil de terrain',
    stability: 'Stabilité',
    drop: 'Drop',
    pending: 'En attente',
    notApplicable: 'Non applicable',
    technologies: 'Construction et technologies',
    ride: 'Sensations et usage',
    sources: 'Sources',
    weight: 'Référence de poids',
    weightValue: 'Poids',
    sourcePending: 'Vérification de la source en attente',
    productOverview: 'Description du produit',
    constructionAndRide: 'Construction et sensations',
    rideCharacter: 'Sensations',
    support: 'Stabilité et guidage',
    upper: 'Tige',
    midsole: 'Semelle intermédiaire',
    outsole: 'Semelle extérieure / adhérence',
    fit: 'Chaussant',
    stackHeight: 'Hauteur de semelle',
    plateSystem: 'Plaque / système',
    strengthsAndLimitations: 'Points forts et limites',
    strengthsLead: 'Synthèse reprise du prototype RunDecoded d’origine.',
    bestAt: 'Particulièrement adaptée à',
    lessSuitableFor: 'Moins adaptée à',
    sourceProduct: 'Voir sur Decathlon',
    prototypeEvidence: 'Données du prototype',
    verifiedEvidence: 'Source produit vérifiée',
    detailsPending:
      'Le prototype d’origine ne contenait pas de fiche détaillée complète pour ce modèle exact. La vérification est en attente.',
    comparableProducts: 'Produits comparables',
    compareWith: (model: string) => `Comparer avec ${model}`,
    openDetails: (model: string) => `Ouvrir les détails de ${model}`,
    productImage: (model: string) => `Image produit de ${model}`,
    imagePending: 'Image produit officielle en attente',
    comparisonTitle: 'Comparaison de chaussures',
    comparisonDescription:
      'Comparez les usages et les faits techniques. Les différences ne remplacent pas un conseil personnalisé.',
    differenceSummary: 'Différences principales',
    characteristic: 'Caractéristique',
    category: 'Catégorie',
    different: 'Différent',
    same: 'Identique',
    notCompared: 'Non comparé',
    weightReferenceMismatch:
      'Les pointures de référence diffèrent, le poids n’est donc pas mis en évidence.',
    selectionLimit:
      'Deux chaussures sont déjà sélectionnées. Retirez-en une avant d’en ajouter une autre.',
  },
} satisfies Record<SupportedLocale, Record<string, unknown>>;

const categoryLabels: Record<string, Record<SupportedLocale, string>> = {
  'daily-trainer': {
    en: 'Daily training',
    de: 'Tägliches Training',
    fr: 'Entraînement quotidien',
  },
  'entry-level': { en: 'Entry level', de: 'Einstieg', fr: 'Débutant' },
  'fast-training': {
    en: 'Fast training',
    de: 'Schnelles Training',
    fr: 'Entraînement rapide',
  },
  'max-cushion': {
    en: 'Max cushion',
    de: 'Maximale Dämpfung',
    fr: 'Amorti maximal',
  },
  race: { en: 'Race', de: 'Wettkampf', fr: 'Compétition' },
  carbon: { en: 'Carbon', de: 'Carbon', fr: 'Carbone' },
  stability: { en: 'Stability', de: 'Stabilität', fr: 'Stabilité' },
  'stability-and-guidance': {
    en: 'Stability & guidance',
    de: 'Stabilität & Führung',
    fr: 'Stabilité et guidage',
  },
  'super-trainer': {
    en: 'Super trainer',
    de: 'Super-Trainer',
    fr: 'Super-trainer',
  },
  support: { en: 'Support', de: 'Support', fr: 'Maintien' },
  trail: { en: 'Trail', de: 'Trail', fr: 'Trail' },
  'trail-race': {
    en: 'Trail race',
    de: 'Trail-Wettkampf',
    fr: 'Compétition trail',
  },
  'technical-trail': {
    en: 'Technical trail',
    de: 'Technischer Trail',
    fr: 'Trail technique',
  },
  'road-to-trail': {
    en: 'Road-to-trail',
    de: 'Road-to-Trail',
    fr: 'Route-trail',
  },
  neutral: { en: 'Neutral', de: 'Neutral', fr: 'Neutre' },
};

export function categoryLabel(
  id: string,
  fallback: string,
  locale: SupportedLocale,
): string {
  return categoryLabels[id]?.[locale] ?? fallback;
}

export function stabilityLabel(value: string, locale: SupportedLocale): string {
  const labels = {
    neutral: { en: 'Neutral', de: 'Neutral', fr: 'Neutre' },
    stability: { en: 'Stability', de: 'Stabilität', fr: 'Stabilité' },
    unknown: { en: 'Pending', de: 'Ausstehend', fr: 'En attente' },
  } as const;
  return labels[value as keyof typeof labels]?.[locale] ?? value;
}

const surfaceFamilyLabels = {
  road: { en: 'Road', de: 'Straße', fr: 'Route' },
  'off-road': {
    en: 'Trail / off-road',
    de: 'Trail / Gelände',
    fr: 'Trail / hors route',
  },
  track: { en: 'Track / spikes', de: 'Bahn / Spikes', fr: 'Piste / pointes' },
} as const;

const terrainProfileLabels = {
  gravel: {
    en: 'Gravel & firm paths',
    de: 'Gravel & feste Wege',
    fr: 'Gravel et chemins fermes',
  },
  'road-to-trail': {
    en: 'Road-to-trail',
    de: 'Road-to-Trail',
    fr: 'Route-trail',
  },
  'easy-terrain': {
    en: 'Easy terrain',
    de: 'Einfaches Gelände',
    fr: 'Terrain facile',
  },
  'mixed-terrain': {
    en: 'Mixed terrain',
    de: 'Gemischtes Gelände',
    fr: 'Terrain mixte',
  },
  'technical-terrain': {
    en: 'Technical terrain',
    de: 'Technisches Gelände',
    fr: 'Terrain technique',
  },
  'muddy-terrain': {
    en: 'Muddy terrain',
    de: 'Schlammiges Gelände',
    fr: 'Terrain boueux',
  },
} as const;

export function surfaceFamilyLabel(
  value: keyof typeof surfaceFamilyLabels,
  locale: SupportedLocale,
): string {
  return surfaceFamilyLabels[value][locale];
}

export function terrainProfileLabel(
  value: keyof typeof terrainProfileLabels,
  locale: SupportedLocale,
): string {
  return terrainProfileLabels[value][locale];
}
